### ISSUE TITLE
Need to connect

### ISSUE THREAD

**Issue by AshvinjeetSingh** [WALIDAZHARI/Crypto-App#1]
Hello Sir,

I was going through your issue in cryto verse app from JS mastery
Is that resolved ?

**Comment by WALIDAZHARI** [comment]
Unfortunately, no, not yet 😢
Any ideas?

**Comment by AshvinjeetSingh** [comment]
No sir
no luck
tried using refetch to clear the existing state of  RTK but was not successful
do let me know if you have any ideas

**Comment by WALIDAZHARI** [comment]
Ok, don't worry, I'll let you know.

**Comment by AshvinjeetSingh** [comment]
Hi @WALIDAZHARI 
it is working now you can find the solution on
https://github.com/adrianhajdin/project_cryptoverse/issues/56

**Comment by WALIDAZHARI** [comment]
really, thank you so much !!!!
